fix pickup of main pb for bosses
randovania/open-dread-rando pull request #175
Opened 2022-12-12 05:34 UTC by ThanatosGit

Smallest possible patch for the bug that bosses do not grant ammo for pbs.

Current logic:
RDV creates something like
```
        {
            "pickup_type": "actor",
            "caption": "Main Power Bomb acquired.",
            "resources": [
                {
                    "item_id": "ITEM_WEAPON_POWER_BOMB",
                    "quantity": 4
                }
            ],
            "pickup_actor": {
                "scenario": "s040_aqua",
                "layer": "default",
                "actor": "item_missiletank_004"
            },
            "model": [
                "powerup_powerbomb"
            ],
            "map_icon": {
                "icon_id": "powerup_powerbomb"
            }
        }
```

where the quantity is set to how many pb tanks you get from main pb. This means the weapon itself is actually mixed with the amount of pb tanks.

For actors the pickup is changed to ITEM_WEAPON_POWER_BOMB_MAX and granting pb tanks instead of main pb.

https://github.com/randovania/open-dread-rando/blob/5e0f174dc8e7b7304c7146a8caa48e10630df8d4/open_dread_rando/pickup.py#L111-L117

The lua script `RandomizerPowerBomb.OnPickedUp` just checks if `ITEM_WEAPON_POWER_BOMB_MAX` was granted and then sets the item amount of main pb to be 1.
https://github.com/randovania/open-dread-rando/blob/5e0f174dc8e7b7304c7146a8caa48e10630df8d4/open_dread_rando/files/randomizer_powerup.lua#L227-L229

-----

If we don't have an actor the replacement described for / in `pickup.py` does not take place and `RandomizerPowerBomb.OnPickedUp` is called like:
```
function RandomizerProgressiveITEM_WEAPON_POWER_BOMB_4.OnPickedUp(actor)
    Game.LogWarn(0, "picked up RandomizerProgressiveITEM_WEAPON_POWER_BOMB_4")
    local progression = {
{
item_id = "ITEM_WEAPON_POWER_BOMB",
quantity = 4,
},
}
    RandomizerPowerBomb.OnPickedUp(actor, progression)
end
```

The patch simply modifies `ITEM_WEAPON_POWER_BOMB` to  `ITEM_WEAPON_POWER_BOMB_MAX` in `RandomizerPowerBomb.OnPickedUp`. So, it will grant pb tanks and because pb tanks are granted, it sets the `ITEM_WEAPON_POWER_BOMB` amount to 1 at the end (like described above).

---

Alternative: Maybe resources should be something like:
```
            "resources": [
                {
                    "item_id": "ITEM_WEAPON_POWER_BOMB_MAX",
                    "quantity": 4
                },
                {
                    "item_id": "ITEM_WEAPON_POWER_BOMB",
                    "quantity": 1
                }
            ],
```
but multiple resourcs are always considered to be a progression and therefore needs a few more changes in the code. If this is preffered, I could do that too.

Therefore I will open this as a draft at first.

2023-01-05 05:57 UTC, duncathan requested changes
> but multiple resourcs are always considered to be a progression and therefore needs a few more changes in the code. If this is preffered, I could do that too.

If it wouldn't be too much trouble, yeah, it'd be preferable to have a more flexible resource system for pickups rather than it only being for progressives. At the minimum we need progressives and simultaneous resources. A sort of "conditional" resource would be cool too - we could use that to implement a main missile launcher item. That's much lower priority though

2023-02-08 08:34 UTC, ThanatosGit commented
Yikes! I read the message but somehow forget to do something or answer. Sorry!

How we could distinguish between progressives and simultaneous resources in odr? I would just add a flag (maybe optional?) to the schema and patch it differently and make some slight modifications from the current implementation to support simultaneous resources. Of course it needs a randovania patch, too.

Considering conditional resources: So better to use an enum instead of a flag for the resource "type". How does a conditional resource work? I just can't imagine what this means. Main missile launcher: Wouldn't that be like power bombs? You collect missiles and can't use them until you collect "ITEM_WEAPON_MISSILE". I don't see the condition in the pickup / resource there but that's maybe because I didn't get the idea at all

2023-02-23 19:31 UTC, duncathan commented
If conditional resources are gonna be too complicated, we can leave them be. Some sort of schema change to differentiate progressives and simultaneous resources is fine by me. Perhaps we make it a list of lists - the outer list is the progressive stages, and the inner lists are the resources granted at each stage?

2023-04-29 21:23 UTC, ThanatosGit commented
Tbh: It's open for quite a while and I was very distracted by the multiworld stuff. I looked at what needs to be done last week but afaik Arcanox is working on a patch very similar to this for the flash shift upgrade. Well, I close this pr because it will clash with that and I also stopped working on it because of that.

2023-04-29 21:23 UTC, closed without merging