Added license to the metadata file
randovania/open-dread-rando pull request #202
Opened 2023-04-01 11:21 UTC by chapnitsky

By adding the license to this file, it will be shown in the website pypi.org It is a part of OSDC course by : @szabgab

2023-04-03 18:39 UTC, henriquegemignani approved these changes

2023-04-03 18:40 UTC, henriquegemignani commented
Thanks!

2023-04-03 20:32 UTC, duncathan requested changes
![Screenshot_20230403_143057_Vivaldi Browser](https://user-images.githubusercontent.com/2979303/229620932-a2d12f16-72a3-47f3-b411-dca1117efb0b.png)
seems things aren't quite so simple

2023-04-06 15:57 UTC, szabgab commented
I think this failure was due to another change that was already on the main branch. Updating the branch of the PR from the original repo will probably trigger a new run of the CI system.

2023-04-28 11:27 UTC, closed without merging