Add "Pride Missiles" cosmetic option to randomize small missile expansion colors
randovania/open-dread-rando pull request #229
Opened 2023-06-04 06:50 UTC by steven11sjf

A new `pride_missiles` cosmetic option allows the patcher to randomize each missile pack to red (default), orange, yellow, green, blue or purple/violet. 

I decided to randomize patches within ODR instead of randomizing in RDV. I think it'd be needlessly complex to add multiple color variants in the generator, and having it in a cosmetic option makes more sense to me for what it does. This means two patches off the same config will have different-colored missile expansions, but I think it's an acceptable trade-off. 

![image](https://github.com/randovania/open-dread-rando/assets/25016775/72f37f6b-807a-4cae-81fc-80fe5cb4218b)
![image](https://github.com/randovania/open-dread-rando/assets/25016775/20abe368-9c66-4287-ada8-5e146a5ea7c0)
![image](https://github.com/randovania/open-dread-rando/assets/25016775/5b4c7315-beb1-43a8-ae16-8b0b0abc389c)
![image](https://github.com/randovania/open-dread-rando/assets/25016775/a43aa183-8716-4f13-b882-8a8eaafdc1c9)
![image](https://github.com/randovania/open-dread-rando/assets/25016775/dc06f41b-0007-4c04-986f-00c48d88f09c)

2023-06-04 06:54 UTC, duncathan requested changes
the normal method for doing something like this would be to generate a random number in Randovania, and pass that number to the patcher to use as the seed for an RNG object

~~also we need more flags~~

2023-06-04 06:56 UTC, steven11sjf commented
> the normal method for doing something like this would be to generate a random number in Randovania, and pass that number to the patcher to use as the seed for an RNG object
> 
> ~also we need more flags~

Ah, I can add that too. Also yeah, though i'm not sure where we could put flags in the game. I guess we could do the banner in the new game UI?

2023-06-04 06:57 UTC, duncathan commented
mostly I was thinking other flags for the missiles. rainbow missiles, trans missiles, nb missiles, etc

2023-06-04 18:00 UTC, henriquegemignani commented
A more flexible way is to just expose all these different models directly and have rdv color each pickup directly however it wants.

2023-06-05 01:11 UTC, steven11sjf commented
Can you point me towards where to do that? I assume it's in the generator which I haven't really looked into a ton before.

2023-06-05 07:51 UTC, henriquegemignani commented
> Can you point me towards where to do that? I assume it's in the generator which I haven't really looked into a ton before.

re-looking to this PR, all you'd need to do in ODR is the new model data entries you added.
For rdv, you'd add some special casing similar to what you did here, but [here](https://github.com/randovania/randovania/blob/main/randovania/games/dread/exporter/patch_data_factory.py#L234-L247) instead.
Not very different to how we do the [shiny missiles for Prime 1](https://github.com/randovania/randovania/blob/main/randovania/games/prime1/exporter/patch_data_factory.py#L133-L138).

2023-06-08 12:54 UTC, henriquegemignani requested changes

2023-06-08 12:54 UTC, henriquegemignani commented on open_dread_rando/missile_color_patcher.py
> +class MissileVariant(Enum):
I'm not sure enums are the best case for this. Could have a dataclass with the mat_name/shader_path/rgba fields, and a global dict of all instances

2023-06-08 12:54 UTC, henriquegemignani commented on open_dread_rando/missile_color_patcher.py
> +            raise ValueError(f"Missile Variant {self.name} has {len(color)} values for RGBA, 4 is expected.")
Typing could be a `tuple[float, float, float, float]`, would indicate this better.

2023-06-08 20:33 UTC, merged