Use keystone only when building the package
randovania/open-dread-rando pull request #258
Opened 2023-08-23 20:48 UTC by henriquegemignani

2023-08-23 20:53 UTC, duncathan requested changes

2023-08-23 20:53 UTC, duncathan commented on tools/debug_input.s
could we keep these in the exefs folder? or at least put them in a folder in tools?

2023-08-23 20:57 UTC, henriquegemignani commented on tools/debug_input.s
done

2023-08-28 21:23 UTC, duncathan approved these changes
approving this but I'd like to hold off on merging until RDV 6.2 since there's still a fix I wanna push through for it

2023-09-10 15:09 UTC, merged