Add resources to Metroid DNA pickups
randovania/open-dread-rando pull request #312
Opened 2024-04-11 21:36 UTC by MayberryZoom

As titled, adds resources to Metroid DNA actor pickups. Fixes #143.

I'm opening this as a draft PR to get feedback, partially because I've done a bit of refactoring. Since I'm using what is currently the progressive template, I generalized it into a custom powerup template. This only renames the template itself and a few variable/property names in the Lua editor.

The other reason this is a draft is because I'm having an issue that I can't figure out. With my code changes, picking up DNA from an actor grants a second DNA (seemingly without calling `OnPickedUp()`) after `OnPickedUp()` finishes. This doesn't happen with other pickups, only with DNA. Advice on this would be highly appreciated.

2024-04-11 21:53 UTC, duncathan requested changes
the double item is probably because the actor is granting the item as well, instead of granting `ITEM_NONE` like progressives do

2024-04-11 21:58 UTC, MayberryZoom commented on src/open_dread_rando/pickups/lua_editor.py
> +        parent = pickup_resources[0][0]
What is it then, if not the parent?

2024-04-11 22:03 UTC, duncathan commented on src/open_dread_rando/pickups/lua_editor.py
> +        parent = pickup_resources[0][0]
a single resource, in this case

2024-04-11 22:08 UTC, MayberryZoom commented
Ready for review; double item issue fixed.

2024-04-11 22:19 UTC, duncathan commented on src/open_dread_rando/pickups/lua_editor.py
> +            parent_id = first_resource["item_id"]
nope lol

2024-04-11 22:20 UTC, MayberryZoom commented on src/open_dread_rando/pickups/lua_editor.py
> +            parent_id = first_resource["item_id"]
Just tell me what to name it lol

2024-04-15 21:10 UTC, duncathan requested changes
please fix the ruff errors. you probably don't have pre-commit installed correctly

2024-04-15 22:56 UTC, duncathan approved these changes

2024-04-15 22:57 UTC, merged